version: "3"
services:
  app:
    image: node:12.11.1-alpine
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - postgres
    links:
      - postgres
    networks:
      - nodejs-app-network
    working_dir: /app
    command: npm run dev

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
    networks:
      - nodejs-app-network

networks: 
  nodejs-app-network:
    driver: bridge      